export interface Quote {
  quote: string;
  author: string;
  type: 'pidgin' | 'english';
}

export const quotes: Quote[] = [
  { quote: "No matter how hot your anger be, e no fit boil beans.", author: "Kitchen Logic", type: "pidgin" },
  { quote: "Na condition make crayfish bend.", author: "Reality Check", type: "pidgin" },
  { quote: "If life show you pepper, make pepper soup with am.", author: "Naija Optimism", type: "pidgin" },
  { quote: "Water wey person go drink no go flow pass am.", author: "Destiny", type: "pidgin" },
  { quote: "E go be! Ma fo.", author: "Street Hope", type: "pidgin" },
  { quote: "Small pikin wey wash im hand clean, go chop with elders.", author: "Protocol", type: "pidgin" },
  { quote: "Waitin concern agbero with overload?", author: "Focus", type: "pidgin" },
  { quote: "Pikin wey say im mama no go sleep, sef no go sleep.", author: "Natural Justice", type: "pidgin" },
  { quote: "Every day for the thief, one day for the owner.", author: "Accountability", type: "pidgin" },
  { quote: "Cow wey no get tail, na God dey help am drive fly.", author: "Grace", type: "pidgin" },
  { quote: "The soup wey sweet, na money kill am.", author: "Investment", type: "pidgin" },
  { quote: "Follow person wey know road.", author: "Mentorship", type: "pidgin" },
  { quote: "Dem no dey tell blind man say rain dey fall.", author: "Obvious Truth", type: "pidgin" },
  { quote: "No be every eye wey dey look dey see.", author: "Insight", type: "pidgin" },
  { quote: "The person wey borrow cloth no dey dance too hard for party.", author: "Caution", type: "pidgin" },
  { quote: "Na from clap dem dey start dance.", author: "Process", type: "pidgin" },
  { quote: "Monkey dey work, baboon dey chop.", author: "Reality", type: "pidgin" },
  { quote: "I get am before no be property.", author: "Current State", type: "pidgin" },
  { quote: "Person wey get head no get cap, person wey get cap no get head.", author: "Irony", type: "pidgin" },
  { quote: "No let your right hand know wetin your left hand dey do.", author: "Discretion", type: "pidgin" },
  { quote: "Last last, everybody go chop breakfast.", author: "Life Happens", type: "pidgin" },
  { quote: "Person wey fry corn for night, go know say wind dey blow.", author: "Awareness", type: "pidgin" },
  { quote: "Na from home dem dey carry beauty go outside.", author: "Foundation", type: "pidgin" },
  { quote: "No be by muscle, na by sense.", author: "Strategy", type: "pidgin" },
  { quote: "Snake wey one person see, na rope e be.", author: "Collaboration", type: "pidgin" },
  { quote: "When breeze blow, fowl nyash go open.", author: "The Truth", type: "pidgin" },
  { quote: "Rat wey follow fish enter water, go know say water get weight.", author: "Experience", type: "pidgin" },
  { quote: "Dey your dey, make I dey my dey.", author: "Peace", type: "pidgin" },
  { quote: "Life na turn by turn.", author: "Patience", type: "pidgin" },
  { quote: "No use because of soup burn your house.", author: "Overreaction", type: "pidgin" },
  { quote: "Small body no be sickness.", author: "Perspective", type: "pidgin" },
  { quote: "Better to crawl than to stay for one place.", author: "Progress", type: "pidgin" },
  { quote: "No be who first call police dey win case.", author: "Wisdom", type: "pidgin" },
  { quote: "Dem no dey use hand cover the moon.", author: "Inevitability", type: "pidgin" },
  { quote: "No be everything wey yellow be gold.", author: "Appearance", type: "pidgin" },
  { quote: "Person wey dey find diamonds, no dey fear mud.", author: "Hard Work", type: "pidgin" },
  { quote: "Water wey dey boil, no dey fear fire.", author: "Courage", type: "pidgin" },
  { quote: "No let your yesterday spoil your today.", author: "New Day", type: "pidgin" },
  { quote: "Small fire today, big smoke tomorrow.", author: "Growth", type: "pidgin" },
  { quote: "Na who get patience go drink clean water.", author: "Fortitude", type: "pidgin" },
  { quote: "No be everything person see e dey talk.", author: "Maturity", type: "pidgin" },
  { quote: "A bird for hand better pass ten for bush.", author: "Gratitude", type: "pidgin" },
  { quote: "If you want to chop big, you go work big.", author: "Effort", type: "pidgin" },
  { quote: "The moon dey shine for everybody.", author: "Equality", type: "pidgin" },
  { quote: "No use leg check depth of river.", author: "Prudence", type: "pidgin" },
  { quote: "Empty barrel dey make noise.", author: "Humility", type: "pidgin" },
  { quote: "No be by shouting dem dey win war.", author: "Quiet Strength", type: "pidgin" },
  { quote: "Problem no dey finish, try to dey enjoy.", author: "Balance", type: "pidgin" },
  { quote: "If you no fit run, waka. If you no fit waka, crawl.", author: "Resilience", type: "pidgin" },
  { quote: "No let anybody use your head break coconut.", author: "Self-Worth", type: "pidgin" },

  // --- 50 BEAUTIFUL ENGLISH MOTIVATIONS ---
  { quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt", type: "english" },
  { quote: "Do not wait to strike till the iron is hot; but make it hot by striking.", author: "W.B. Yeats", type: "english" },
  { quote: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs", type: "english" },
  { quote: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair", type: "english" },
  { quote: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill", type: "english" },
  { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs", type: "english" },
  { quote: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe", type: "english" },
  { quote: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Proverb", type: "english" },
  { quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt", type: "english" },
  { quote: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius", type: "english" },
  { quote: "Happiness is not something readymade. It comes from your own actions.", author: "Dalai Lama", type: "english" },
  { quote: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson", type: "english" },
  { quote: "Everything has beauty, but not everyone sees it.", author: "Confucius", type: "english" },
  { quote: "Dream big and dare to fail.", author: "Norman Vaughan", type: "english" },
  { quote: "What we achieve inwardly will change outer reality.", author: "Plutarch", type: "english" },
  { quote: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis", type: "english" },
  { quote: "The power of imagination makes us infinite.", author: "John Muir", type: "english" },
  { quote: "Change your thoughts and you change your world.", author: "Norman Vincent Peale", type: "english" },
  { quote: "Don't count the days, make the days count.", author: "Muhammad Ali", type: "english" },
  { quote: "He who has a why to live can bear almost any how.", author: "Friedrich Nietzsche", type: "english" },
  { quote: "The journey of a thousand miles begins with a single step.", author: "Lao Tzu", type: "english" },
  { quote: "Quality is not an act, it is a habit.", author: "Aristotle", type: "english" },
  { quote: "If you're going through hell, keep going.", author: "Winston Churchill", type: "english" },
  { quote: "The secret of getting ahead is getting started.", author: "Mark Twain", type: "english" },
  { quote: "The only limit to our realization of tomorrow will be our doubts of today.", author: "F.D. Roosevelt", type: "english" },
  { quote: "Act as if what you do makes a difference. It does.", author: "William James", type: "english" },
  { quote: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman", type: "english" },
  { quote: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Emerson", type: "english" },
  { quote: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein", type: "english" },
  { quote: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi", type: "english" },
  { quote: "Limit your 'always' and your 'nevers'.", author: "Amy Poehler", type: "english" },
  { quote: "Life is 10% what happens to me and 90% of how I react to it.", author: "Charles Swindoll", type: "english" },
  { quote: "Your life does not get better by chance, it gets better by change.", author: "Jim Rohn", type: "english" },
  { quote: "The mind is everything. What you think you become.", author: "Buddha", type: "english" },
  { quote: "An unexamined life is not worth living.", author: "Socrates", type: "english" },
  { quote: "Everything you can imagine is real.", author: "Pablo Picasso", type: "english" },
  { quote: "Perfection is not attainable, but if we chase perfection we can catch excellence.", author: "Vince Lombardi", type: "english" },
  { quote: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett", type: "english" },
  { quote: "Fall seven times, stand up eight.", author: "Japanese Proverb", type: "english" },
  { quote: "Opportunities don't happen, you create them.", author: "Chris Grosser", type: "english" },
  { quote: "Go confidently in the direction of your dreams.", author: "Henry David Thoreau", type: "english" },
  { quote: "It always seems impossible until it's done.", author: "Nelson Mandela", type: "english" },
  { quote: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington", type: "english" },
  { quote: "Courage is grace under pressure.", author: "Ernest Hemingway", type: "english" },
  { quote: "Life is either a daring adventure or nothing at all.", author: "Helen Keller", type: "english" },
  { quote: "The way to get started is to quit talking and begin doing.", author: "Walt Disney", type: "english" },
  { quote: "Turn your wounds into wisdom.", author: "Oprah Winfrey", type: "english" },
  { quote: "Wisdom begins in wonder.", author: "Socrates", type: "english" },
  { quote: "Be yourself; everyone else is already taken.", author: "Oscar Wilde", type: "english" },
  { quote: "Make today so awesome yesterday gets jealous.", author: "Unknown", type: "english" }
];